// Code generated by mockery v2.50.0. DO NOT EDIT.

package s3

import (
	clients3 "github.com/fi-ts/cloud-go/api/client/s3"
	mock "github.com/stretchr/testify/mock"

	runtime "github.com/go-openapi/runtime"
)

// ClientService is an autogenerated mock type for the ClientService type
type ClientService struct {
	mock.Mock
}

// Creates3 provides a mock function with given fields: params, authInfo, opts
func (_m *ClientService) Creates3(params *clients3.Creates3Params, authInfo runtime.ClientAuthInfoWriter, opts ...clients3.ClientOption) (*clients3.Creates3OK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params, authInfo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Creates3")
	}

	var r0 *clients3.Creates3OK
	var r1 error
	if rf, ok := ret.Get(0).(func(*clients3.Creates3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) (*clients3.Creates3OK, error)); ok {
		return rf(params, authInfo, opts...)
	}
	if rf, ok := ret.Get(0).(func(*clients3.Creates3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) *clients3.Creates3OK); ok {
		r0 = rf(params, authInfo, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients3.Creates3OK)
		}
	}

	if rf, ok := ret.Get(1).(func(*clients3.Creates3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) error); ok {
		r1 = rf(params, authInfo, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Deletes3 provides a mock function with given fields: params, authInfo, opts
func (_m *ClientService) Deletes3(params *clients3.Deletes3Params, authInfo runtime.ClientAuthInfoWriter, opts ...clients3.ClientOption) (*clients3.Deletes3OK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params, authInfo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Deletes3")
	}

	var r0 *clients3.Deletes3OK
	var r1 error
	if rf, ok := ret.Get(0).(func(*clients3.Deletes3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) (*clients3.Deletes3OK, error)); ok {
		return rf(params, authInfo, opts...)
	}
	if rf, ok := ret.Get(0).(func(*clients3.Deletes3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) *clients3.Deletes3OK); ok {
		r0 = rf(params, authInfo, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients3.Deletes3OK)
		}
	}

	if rf, ok := ret.Get(1).(func(*clients3.Deletes3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) error); ok {
		r1 = rf(params, authInfo, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Gets3 provides a mock function with given fields: params, authInfo, opts
func (_m *ClientService) Gets3(params *clients3.Gets3Params, authInfo runtime.ClientAuthInfoWriter, opts ...clients3.ClientOption) (*clients3.Gets3OK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params, authInfo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Gets3")
	}

	var r0 *clients3.Gets3OK
	var r1 error
	if rf, ok := ret.Get(0).(func(*clients3.Gets3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) (*clients3.Gets3OK, error)); ok {
		return rf(params, authInfo, opts...)
	}
	if rf, ok := ret.Get(0).(func(*clients3.Gets3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) *clients3.Gets3OK); ok {
		r0 = rf(params, authInfo, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients3.Gets3OK)
		}
	}

	if rf, ok := ret.Get(1).(func(*clients3.Gets3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) error); ok {
		r1 = rf(params, authInfo, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lists3 provides a mock function with given fields: params, authInfo, opts
func (_m *ClientService) Lists3(params *clients3.Lists3Params, authInfo runtime.ClientAuthInfoWriter, opts ...clients3.ClientOption) (*clients3.Lists3OK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params, authInfo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Lists3")
	}

	var r0 *clients3.Lists3OK
	var r1 error
	if rf, ok := ret.Get(0).(func(*clients3.Lists3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) (*clients3.Lists3OK, error)); ok {
		return rf(params, authInfo, opts...)
	}
	if rf, ok := ret.Get(0).(func(*clients3.Lists3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) *clients3.Lists3OK); ok {
		r0 = rf(params, authInfo, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients3.Lists3OK)
		}
	}

	if rf, ok := ret.Get(1).(func(*clients3.Lists3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) error); ok {
		r1 = rf(params, authInfo, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lists3partitions provides a mock function with given fields: params, authInfo, opts
func (_m *ClientService) Lists3partitions(params *clients3.Lists3partitionsParams, authInfo runtime.ClientAuthInfoWriter, opts ...clients3.ClientOption) (*clients3.Lists3partitionsOK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params, authInfo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Lists3partitions")
	}

	var r0 *clients3.Lists3partitionsOK
	var r1 error
	if rf, ok := ret.Get(0).(func(*clients3.Lists3partitionsParams, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) (*clients3.Lists3partitionsOK, error)); ok {
		return rf(params, authInfo, opts...)
	}
	if rf, ok := ret.Get(0).(func(*clients3.Lists3partitionsParams, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) *clients3.Lists3partitionsOK); ok {
		r0 = rf(params, authInfo, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients3.Lists3partitionsOK)
		}
	}

	if rf, ok := ret.Get(1).(func(*clients3.Lists3partitionsParams, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) error); ok {
		r1 = rf(params, authInfo, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetTransport provides a mock function with given fields: transport
func (_m *ClientService) SetTransport(transport runtime.ClientTransport) {
	_m.Called(transport)
}

// Updates3 provides a mock function with given fields: params, authInfo, opts
func (_m *ClientService) Updates3(params *clients3.Updates3Params, authInfo runtime.ClientAuthInfoWriter, opts ...clients3.ClientOption) (*clients3.Updates3OK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params, authInfo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Updates3")
	}

	var r0 *clients3.Updates3OK
	var r1 error
	if rf, ok := ret.Get(0).(func(*clients3.Updates3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) (*clients3.Updates3OK, error)); ok {
		return rf(params, authInfo, opts...)
	}
	if rf, ok := ret.Get(0).(func(*clients3.Updates3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) *clients3.Updates3OK); ok {
		r0 = rf(params, authInfo, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients3.Updates3OK)
		}
	}

	if rf, ok := ret.Get(1).(func(*clients3.Updates3Params, runtime.ClientAuthInfoWriter, ...clients3.ClientOption) error); ok {
		r1 = rf(params, authInfo, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientService creates a new instance of ClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientService {
	mock := &ClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
