// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
)

// NewCycleMachineParams creates a new CycleMachineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCycleMachineParams() *CycleMachineParams {
	return &CycleMachineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCycleMachineParamsWithTimeout creates a new CycleMachineParams object
// with the ability to set a timeout on a request.
func NewCycleMachineParamsWithTimeout(timeout time.Duration) *CycleMachineParams {
	return &CycleMachineParams{
		timeout: timeout,
	}
}

// NewCycleMachineParamsWithContext creates a new CycleMachineParams object
// with the ability to set a context for a request.
func NewCycleMachineParamsWithContext(ctx context.Context) *CycleMachineParams {
	return &CycleMachineParams{
		Context: ctx,
	}
}

// NewCycleMachineParamsWithHTTPClient creates a new CycleMachineParams object
// with the ability to set a custom HTTPClient for a request.
func NewCycleMachineParamsWithHTTPClient(client *http.Client) *CycleMachineParams {
	return &CycleMachineParams{
		HTTPClient: client,
	}
}

/*
CycleMachineParams contains all the parameters to send to the API endpoint

	for the cycle machine operation.

	Typically these are written to a http.Request.
*/
type CycleMachineParams struct {

	// Body.
	Body *models.V1ClusterMachineCycleRequest

	/* ID.

	   identifier of the cluster
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cycle machine params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CycleMachineParams) WithDefaults() *CycleMachineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cycle machine params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CycleMachineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cycle machine params
func (o *CycleMachineParams) WithTimeout(timeout time.Duration) *CycleMachineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cycle machine params
func (o *CycleMachineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cycle machine params
func (o *CycleMachineParams) WithContext(ctx context.Context) *CycleMachineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cycle machine params
func (o *CycleMachineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cycle machine params
func (o *CycleMachineParams) WithHTTPClient(client *http.Client) *CycleMachineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cycle machine params
func (o *CycleMachineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the cycle machine params
func (o *CycleMachineParams) WithBody(body *models.V1ClusterMachineCycleRequest) *CycleMachineParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the cycle machine params
func (o *CycleMachineParams) SetBody(body *models.V1ClusterMachineCycleRequest) {
	o.Body = body
}

// WithID adds the id to the cycle machine params
func (o *CycleMachineParams) WithID(id string) *CycleMachineParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the cycle machine params
func (o *CycleMachineParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CycleMachineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
