// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/metal-stack/cloud-go/api/models"
)

// GetSSHKeyPairReader is a Reader for the GetSSHKeyPair structure.
type GetSSHKeyPairReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSSHKeyPairReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSSHKeyPairOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetSSHKeyPairDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSSHKeyPairOK creates a GetSSHKeyPairOK with default headers values
func NewGetSSHKeyPairOK() *GetSSHKeyPairOK {
	return &GetSSHKeyPairOK{}
}

/*GetSSHKeyPairOK handles this case with default header values.

OK
*/
type GetSSHKeyPairOK struct {
	Payload *models.V1ClusterCredentialsResponse
}

func (o *GetSSHKeyPairOK) Error() string {
	return fmt.Sprintf("[GET /v1/cluster/{id}/sshkeypair][%d] getSshKeyPairOK  %+v", 200, o.Payload)
}

func (o *GetSSHKeyPairOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ClusterCredentialsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSSHKeyPairDefault creates a GetSSHKeyPairDefault with default headers values
func NewGetSSHKeyPairDefault(code int) *GetSSHKeyPairDefault {
	return &GetSSHKeyPairDefault{
		_statusCode: code,
	}
}

/*GetSSHKeyPairDefault handles this case with default header values.

Error
*/
type GetSSHKeyPairDefault struct {
	_statusCode int

	Payload *models.HttperrorsHTTPErrorResponse
}

// Code gets the status code for the get SSH key pair default response
func (o *GetSSHKeyPairDefault) Code() int {
	return o._statusCode
}

func (o *GetSSHKeyPairDefault) Error() string {
	return fmt.Sprintf("[GET /v1/cluster/{id}/sshkeypair][%d] getSSHKeyPair default  %+v", o._statusCode, o.Payload)
}

func (o *GetSSHKeyPairDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttperrorsHTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
