// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMonitoringSecretParams creates a new GetMonitoringSecretParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMonitoringSecretParams() *GetMonitoringSecretParams {
	return &GetMonitoringSecretParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMonitoringSecretParamsWithTimeout creates a new GetMonitoringSecretParams object
// with the ability to set a timeout on a request.
func NewGetMonitoringSecretParamsWithTimeout(timeout time.Duration) *GetMonitoringSecretParams {
	return &GetMonitoringSecretParams{
		timeout: timeout,
	}
}

// NewGetMonitoringSecretParamsWithContext creates a new GetMonitoringSecretParams object
// with the ability to set a context for a request.
func NewGetMonitoringSecretParamsWithContext(ctx context.Context) *GetMonitoringSecretParams {
	return &GetMonitoringSecretParams{
		Context: ctx,
	}
}

// NewGetMonitoringSecretParamsWithHTTPClient creates a new GetMonitoringSecretParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMonitoringSecretParamsWithHTTPClient(client *http.Client) *GetMonitoringSecretParams {
	return &GetMonitoringSecretParams{
		HTTPClient: client,
	}
}

/* GetMonitoringSecretParams contains all the parameters to send to the API endpoint
   for the get monitoring secret operation.

   Typically these are written to a http.Request.
*/
type GetMonitoringSecretParams struct {

	/* ID.

	   identifier of the cluster
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get monitoring secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMonitoringSecretParams) WithDefaults() *GetMonitoringSecretParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get monitoring secret params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMonitoringSecretParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get monitoring secret params
func (o *GetMonitoringSecretParams) WithTimeout(timeout time.Duration) *GetMonitoringSecretParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get monitoring secret params
func (o *GetMonitoringSecretParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get monitoring secret params
func (o *GetMonitoringSecretParams) WithContext(ctx context.Context) *GetMonitoringSecretParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get monitoring secret params
func (o *GetMonitoringSecretParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get monitoring secret params
func (o *GetMonitoringSecretParams) WithHTTPClient(client *http.Client) *GetMonitoringSecretParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get monitoring secret params
func (o *GetMonitoringSecretParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get monitoring secret params
func (o *GetMonitoringSecretParams) WithID(id string) *GetMonitoringSecretParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get monitoring secret params
func (o *GetMonitoringSecretParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetMonitoringSecretParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
