// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
)

// NewCreatePostgresParams creates a new CreatePostgresParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePostgresParams() *CreatePostgresParams {
	return &CreatePostgresParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePostgresParamsWithTimeout creates a new CreatePostgresParams object
// with the ability to set a timeout on a request.
func NewCreatePostgresParamsWithTimeout(timeout time.Duration) *CreatePostgresParams {
	return &CreatePostgresParams{
		timeout: timeout,
	}
}

// NewCreatePostgresParamsWithContext creates a new CreatePostgresParams object
// with the ability to set a context for a request.
func NewCreatePostgresParamsWithContext(ctx context.Context) *CreatePostgresParams {
	return &CreatePostgresParams{
		Context: ctx,
	}
}

// NewCreatePostgresParamsWithHTTPClient creates a new CreatePostgresParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePostgresParamsWithHTTPClient(client *http.Client) *CreatePostgresParams {
	return &CreatePostgresParams{
		HTTPClient: client,
	}
}

/*
CreatePostgresParams contains all the parameters to send to the API endpoint

	for the create postgres operation.

	Typically these are written to a http.Request.
*/
type CreatePostgresParams struct {

	// Body.
	Body *models.V1PostgresCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create postgres params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePostgresParams) WithDefaults() *CreatePostgresParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create postgres params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePostgresParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create postgres params
func (o *CreatePostgresParams) WithTimeout(timeout time.Duration) *CreatePostgresParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create postgres params
func (o *CreatePostgresParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create postgres params
func (o *CreatePostgresParams) WithContext(ctx context.Context) *CreatePostgresParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create postgres params
func (o *CreatePostgresParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create postgres params
func (o *CreatePostgresParams) WithHTTPClient(client *http.Client) *CreatePostgresParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create postgres params
func (o *CreatePostgresParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create postgres params
func (o *CreatePostgresParams) WithBody(body *models.V1PostgresCreateRequest) *CreatePostgresParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create postgres params
func (o *CreatePostgresParams) SetBody(body *models.V1PostgresCreateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePostgresParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
