// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
)

// NewCreatePostgresBackupConfigParams creates a new CreatePostgresBackupConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreatePostgresBackupConfigParams() *CreatePostgresBackupConfigParams {
	return &CreatePostgresBackupConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePostgresBackupConfigParamsWithTimeout creates a new CreatePostgresBackupConfigParams object
// with the ability to set a timeout on a request.
func NewCreatePostgresBackupConfigParamsWithTimeout(timeout time.Duration) *CreatePostgresBackupConfigParams {
	return &CreatePostgresBackupConfigParams{
		timeout: timeout,
	}
}

// NewCreatePostgresBackupConfigParamsWithContext creates a new CreatePostgresBackupConfigParams object
// with the ability to set a context for a request.
func NewCreatePostgresBackupConfigParamsWithContext(ctx context.Context) *CreatePostgresBackupConfigParams {
	return &CreatePostgresBackupConfigParams{
		Context: ctx,
	}
}

// NewCreatePostgresBackupConfigParamsWithHTTPClient creates a new CreatePostgresBackupConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreatePostgresBackupConfigParamsWithHTTPClient(client *http.Client) *CreatePostgresBackupConfigParams {
	return &CreatePostgresBackupConfigParams{
		HTTPClient: client,
	}
}

/* CreatePostgresBackupConfigParams contains all the parameters to send to the API endpoint
   for the create postgres backup config operation.

   Typically these are written to a http.Request.
*/
type CreatePostgresBackupConfigParams struct {

	// Body.
	Body *models.V1PostgresBackupConfigCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create postgres backup config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePostgresBackupConfigParams) WithDefaults() *CreatePostgresBackupConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create postgres backup config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreatePostgresBackupConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create postgres backup config params
func (o *CreatePostgresBackupConfigParams) WithTimeout(timeout time.Duration) *CreatePostgresBackupConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create postgres backup config params
func (o *CreatePostgresBackupConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create postgres backup config params
func (o *CreatePostgresBackupConfigParams) WithContext(ctx context.Context) *CreatePostgresBackupConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create postgres backup config params
func (o *CreatePostgresBackupConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create postgres backup config params
func (o *CreatePostgresBackupConfigParams) WithHTTPClient(client *http.Client) *CreatePostgresBackupConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create postgres backup config params
func (o *CreatePostgresBackupConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create postgres backup config params
func (o *CreatePostgresBackupConfigParams) WithBody(body *models.V1PostgresBackupConfigCreateRequest) *CreatePostgresBackupConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create postgres backup config params
func (o *CreatePostgresBackupConfigParams) SetBody(body *models.V1PostgresBackupConfigCreateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePostgresBackupConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
