// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBackupConfigParams creates a new GetBackupConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBackupConfigParams() *GetBackupConfigParams {
	return &GetBackupConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBackupConfigParamsWithTimeout creates a new GetBackupConfigParams object
// with the ability to set a timeout on a request.
func NewGetBackupConfigParamsWithTimeout(timeout time.Duration) *GetBackupConfigParams {
	return &GetBackupConfigParams{
		timeout: timeout,
	}
}

// NewGetBackupConfigParamsWithContext creates a new GetBackupConfigParams object
// with the ability to set a context for a request.
func NewGetBackupConfigParamsWithContext(ctx context.Context) *GetBackupConfigParams {
	return &GetBackupConfigParams{
		Context: ctx,
	}
}

// NewGetBackupConfigParamsWithHTTPClient creates a new GetBackupConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBackupConfigParamsWithHTTPClient(client *http.Client) *GetBackupConfigParams {
	return &GetBackupConfigParams{
		HTTPClient: client,
	}
}

/* GetBackupConfigParams contains all the parameters to send to the API endpoint
   for the get backup config operation.

   Typically these are written to a http.Request.
*/
type GetBackupConfigParams struct {

	/* ID.

	   identifier of the backup
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get backup config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBackupConfigParams) WithDefaults() *GetBackupConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get backup config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBackupConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get backup config params
func (o *GetBackupConfigParams) WithTimeout(timeout time.Duration) *GetBackupConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get backup config params
func (o *GetBackupConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get backup config params
func (o *GetBackupConfigParams) WithContext(ctx context.Context) *GetBackupConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get backup config params
func (o *GetBackupConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get backup config params
func (o *GetBackupConfigParams) WithHTTPClient(client *http.Client) *GetBackupConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get backup config params
func (o *GetBackupConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get backup config params
func (o *GetBackupConfigParams) WithID(id string) *GetBackupConfigParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get backup config params
func (o *GetBackupConfigParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBackupConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
