// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPostgresBackupsParams creates a new GetPostgresBackupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPostgresBackupsParams() *GetPostgresBackupsParams {
	return &GetPostgresBackupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPostgresBackupsParamsWithTimeout creates a new GetPostgresBackupsParams object
// with the ability to set a timeout on a request.
func NewGetPostgresBackupsParamsWithTimeout(timeout time.Duration) *GetPostgresBackupsParams {
	return &GetPostgresBackupsParams{
		timeout: timeout,
	}
}

// NewGetPostgresBackupsParamsWithContext creates a new GetPostgresBackupsParams object
// with the ability to set a context for a request.
func NewGetPostgresBackupsParamsWithContext(ctx context.Context) *GetPostgresBackupsParams {
	return &GetPostgresBackupsParams{
		Context: ctx,
	}
}

// NewGetPostgresBackupsParamsWithHTTPClient creates a new GetPostgresBackupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPostgresBackupsParamsWithHTTPClient(client *http.Client) *GetPostgresBackupsParams {
	return &GetPostgresBackupsParams{
		HTTPClient: client,
	}
}

/* GetPostgresBackupsParams contains all the parameters to send to the API endpoint
   for the get postgres backups operation.

   Typically these are written to a http.Request.
*/
type GetPostgresBackupsParams struct {

	/* ID.

	   identifier of the postgres
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get postgres backups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPostgresBackupsParams) WithDefaults() *GetPostgresBackupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get postgres backups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPostgresBackupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get postgres backups params
func (o *GetPostgresBackupsParams) WithTimeout(timeout time.Duration) *GetPostgresBackupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get postgres backups params
func (o *GetPostgresBackupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get postgres backups params
func (o *GetPostgresBackupsParams) WithContext(ctx context.Context) *GetPostgresBackupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get postgres backups params
func (o *GetPostgresBackupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get postgres backups params
func (o *GetPostgresBackupsParams) WithHTTPClient(client *http.Client) *GetPostgresBackupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get postgres backups params
func (o *GetPostgresBackupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get postgres backups params
func (o *GetPostgresBackupsParams) WithID(id string) *GetPostgresBackupsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get postgres backups params
func (o *GetPostgresBackupsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPostgresBackupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
