// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// RestorePostgresReader is a Reader for the RestorePostgres structure.
type RestorePostgresReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestorePostgresReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewRestorePostgresCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRestorePostgresDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRestorePostgresCreated creates a RestorePostgresCreated with default headers values
func NewRestorePostgresCreated() *RestorePostgresCreated {
	return &RestorePostgresCreated{}
}

/*
RestorePostgresCreated describes a response with status code 201, with default header values.

Created
*/
type RestorePostgresCreated struct {
	Payload *models.V1PostgresResponse
}

// IsSuccess returns true when this restore postgres created response has a 2xx status code
func (o *RestorePostgresCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this restore postgres created response has a 3xx status code
func (o *RestorePostgresCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this restore postgres created response has a 4xx status code
func (o *RestorePostgresCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this restore postgres created response has a 5xx status code
func (o *RestorePostgresCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this restore postgres created response a status code equal to that given
func (o *RestorePostgresCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the restore postgres created response
func (o *RestorePostgresCreated) Code() int {
	return 201
}

func (o *RestorePostgresCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/database/postgres/restore][%d] restorePostgresCreated %s", 201, payload)
}

func (o *RestorePostgresCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/database/postgres/restore][%d] restorePostgresCreated %s", 201, payload)
}

func (o *RestorePostgresCreated) GetPayload() *models.V1PostgresResponse {
	return o.Payload
}

func (o *RestorePostgresCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1PostgresResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRestorePostgresDefault creates a RestorePostgresDefault with default headers values
func NewRestorePostgresDefault(code int) *RestorePostgresDefault {
	return &RestorePostgresDefault{
		_statusCode: code,
	}
}

/*
RestorePostgresDefault describes a response with status code -1, with default header values.

Error
*/
type RestorePostgresDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// IsSuccess returns true when this restore postgres default response has a 2xx status code
func (o *RestorePostgresDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this restore postgres default response has a 3xx status code
func (o *RestorePostgresDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this restore postgres default response has a 4xx status code
func (o *RestorePostgresDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this restore postgres default response has a 5xx status code
func (o *RestorePostgresDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this restore postgres default response a status code equal to that given
func (o *RestorePostgresDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the restore postgres default response
func (o *RestorePostgresDefault) Code() int {
	return o._statusCode
}

func (o *RestorePostgresDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/database/postgres/restore][%d] restorePostgres default %s", o._statusCode, payload)
}

func (o *RestorePostgresDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /v1/database/postgres/restore][%d] restorePostgres default %s", o._statusCode, payload)
}

func (o *RestorePostgresDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *RestorePostgresDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
