// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// UpdatePostgresBackupConfigReader is a Reader for the UpdatePostgresBackupConfig structure.
type UpdatePostgresBackupConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdatePostgresBackupConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdatePostgresBackupConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdatePostgresBackupConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdatePostgresBackupConfigOK creates a UpdatePostgresBackupConfigOK with default headers values
func NewUpdatePostgresBackupConfigOK() *UpdatePostgresBackupConfigOK {
	return &UpdatePostgresBackupConfigOK{}
}

/*
	UpdatePostgresBackupConfigOK describes a response with status code 200, with default header values.

OK
*/
type UpdatePostgresBackupConfigOK struct {
	Payload *models.V1PostgresBackupConfigResponse
}

func (o *UpdatePostgresBackupConfigOK) Error() string {
	return fmt.Sprintf("[POST /v1/database/postgres/backup-config][%d] updatePostgresBackupConfigOK  %+v", 200, o.Payload)
}
func (o *UpdatePostgresBackupConfigOK) GetPayload() *models.V1PostgresBackupConfigResponse {
	return o.Payload
}

func (o *UpdatePostgresBackupConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1PostgresBackupConfigResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdatePostgresBackupConfigDefault creates a UpdatePostgresBackupConfigDefault with default headers values
func NewUpdatePostgresBackupConfigDefault(code int) *UpdatePostgresBackupConfigDefault {
	return &UpdatePostgresBackupConfigDefault{
		_statusCode: code,
	}
}

/*
	UpdatePostgresBackupConfigDefault describes a response with status code -1, with default header values.

Error
*/
type UpdatePostgresBackupConfigDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the update postgres backup config default response
func (o *UpdatePostgresBackupConfigDefault) Code() int {
	return o._statusCode
}

func (o *UpdatePostgresBackupConfigDefault) Error() string {
	return fmt.Sprintf("[POST /v1/database/postgres/backup-config][%d] updatePostgresBackupConfig default  %+v", o._statusCode, o.Payload)
}
func (o *UpdatePostgresBackupConfigDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *UpdatePostgresBackupConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
