// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
)

// NewUpdatePostgresBackupConfigParams creates a new UpdatePostgresBackupConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdatePostgresBackupConfigParams() *UpdatePostgresBackupConfigParams {
	return &UpdatePostgresBackupConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePostgresBackupConfigParamsWithTimeout creates a new UpdatePostgresBackupConfigParams object
// with the ability to set a timeout on a request.
func NewUpdatePostgresBackupConfigParamsWithTimeout(timeout time.Duration) *UpdatePostgresBackupConfigParams {
	return &UpdatePostgresBackupConfigParams{
		timeout: timeout,
	}
}

// NewUpdatePostgresBackupConfigParamsWithContext creates a new UpdatePostgresBackupConfigParams object
// with the ability to set a context for a request.
func NewUpdatePostgresBackupConfigParamsWithContext(ctx context.Context) *UpdatePostgresBackupConfigParams {
	return &UpdatePostgresBackupConfigParams{
		Context: ctx,
	}
}

// NewUpdatePostgresBackupConfigParamsWithHTTPClient creates a new UpdatePostgresBackupConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdatePostgresBackupConfigParamsWithHTTPClient(client *http.Client) *UpdatePostgresBackupConfigParams {
	return &UpdatePostgresBackupConfigParams{
		HTTPClient: client,
	}
}

/* UpdatePostgresBackupConfigParams contains all the parameters to send to the API endpoint
   for the update postgres backup config operation.

   Typically these are written to a http.Request.
*/
type UpdatePostgresBackupConfigParams struct {

	// Body.
	Body *models.V1BackupUpdateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update postgres backup config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePostgresBackupConfigParams) WithDefaults() *UpdatePostgresBackupConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update postgres backup config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePostgresBackupConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update postgres backup config params
func (o *UpdatePostgresBackupConfigParams) WithTimeout(timeout time.Duration) *UpdatePostgresBackupConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update postgres backup config params
func (o *UpdatePostgresBackupConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update postgres backup config params
func (o *UpdatePostgresBackupConfigParams) WithContext(ctx context.Context) *UpdatePostgresBackupConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update postgres backup config params
func (o *UpdatePostgresBackupConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update postgres backup config params
func (o *UpdatePostgresBackupConfigParams) WithHTTPClient(client *http.Client) *UpdatePostgresBackupConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update postgres backup config params
func (o *UpdatePostgresBackupConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update postgres backup config params
func (o *UpdatePostgresBackupConfigParams) WithBody(body *models.V1BackupUpdateRequest) *UpdatePostgresBackupConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update postgres backup config params
func (o *UpdatePostgresBackupConfigParams) SetBody(body *models.V1BackupUpdateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePostgresBackupConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
