// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
)

// NewMachineReservationsUsageParams creates a new MachineReservationsUsageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMachineReservationsUsageParams() *MachineReservationsUsageParams {
	return &MachineReservationsUsageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMachineReservationsUsageParamsWithTimeout creates a new MachineReservationsUsageParams object
// with the ability to set a timeout on a request.
func NewMachineReservationsUsageParamsWithTimeout(timeout time.Duration) *MachineReservationsUsageParams {
	return &MachineReservationsUsageParams{
		timeout: timeout,
	}
}

// NewMachineReservationsUsageParamsWithContext creates a new MachineReservationsUsageParams object
// with the ability to set a context for a request.
func NewMachineReservationsUsageParamsWithContext(ctx context.Context) *MachineReservationsUsageParams {
	return &MachineReservationsUsageParams{
		Context: ctx,
	}
}

// NewMachineReservationsUsageParamsWithHTTPClient creates a new MachineReservationsUsageParams object
// with the ability to set a custom HTTPClient for a request.
func NewMachineReservationsUsageParamsWithHTTPClient(client *http.Client) *MachineReservationsUsageParams {
	return &MachineReservationsUsageParams{
		HTTPClient: client,
	}
}

/*
MachineReservationsUsageParams contains all the parameters to send to the API endpoint

	for the machine reservations usage operation.

	Typically these are written to a http.Request.
*/
type MachineReservationsUsageParams struct {

	// Body.
	Body *models.V1MachineReservationFindRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the machine reservations usage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachineReservationsUsageParams) WithDefaults() *MachineReservationsUsageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the machine reservations usage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MachineReservationsUsageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the machine reservations usage params
func (o *MachineReservationsUsageParams) WithTimeout(timeout time.Duration) *MachineReservationsUsageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the machine reservations usage params
func (o *MachineReservationsUsageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the machine reservations usage params
func (o *MachineReservationsUsageParams) WithContext(ctx context.Context) *MachineReservationsUsageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the machine reservations usage params
func (o *MachineReservationsUsageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the machine reservations usage params
func (o *MachineReservationsUsageParams) WithHTTPClient(client *http.Client) *MachineReservationsUsageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the machine reservations usage params
func (o *MachineReservationsUsageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the machine reservations usage params
func (o *MachineReservationsUsageParams) WithBody(body *models.V1MachineReservationFindRequest) *MachineReservationsUsageParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the machine reservations usage params
func (o *MachineReservationsUsageParams) SetBody(body *models.V1MachineReservationFindRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *MachineReservationsUsageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
