// Code generated by go-swagger; DO NOT EDIT.

package accounting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
)

// NewClusterUsageCSVParams creates a new ClusterUsageCSVParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewClusterUsageCSVParams() *ClusterUsageCSVParams {
	return &ClusterUsageCSVParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewClusterUsageCSVParamsWithTimeout creates a new ClusterUsageCSVParams object
// with the ability to set a timeout on a request.
func NewClusterUsageCSVParamsWithTimeout(timeout time.Duration) *ClusterUsageCSVParams {
	return &ClusterUsageCSVParams{
		timeout: timeout,
	}
}

// NewClusterUsageCSVParamsWithContext creates a new ClusterUsageCSVParams object
// with the ability to set a context for a request.
func NewClusterUsageCSVParamsWithContext(ctx context.Context) *ClusterUsageCSVParams {
	return &ClusterUsageCSVParams{
		Context: ctx,
	}
}

// NewClusterUsageCSVParamsWithHTTPClient creates a new ClusterUsageCSVParams object
// with the ability to set a custom HTTPClient for a request.
func NewClusterUsageCSVParamsWithHTTPClient(client *http.Client) *ClusterUsageCSVParams {
	return &ClusterUsageCSVParams{
		HTTPClient: client,
	}
}

/*
ClusterUsageCSVParams contains all the parameters to send to the API endpoint

	for the cluster usage c s v operation.

	Typically these are written to a http.Request.
*/
type ClusterUsageCSVParams struct {

	// Body.
	Body *models.V1ClusterUsageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cluster usage c s v params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClusterUsageCSVParams) WithDefaults() *ClusterUsageCSVParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cluster usage c s v params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClusterUsageCSVParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cluster usage c s v params
func (o *ClusterUsageCSVParams) WithTimeout(timeout time.Duration) *ClusterUsageCSVParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cluster usage c s v params
func (o *ClusterUsageCSVParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cluster usage c s v params
func (o *ClusterUsageCSVParams) WithContext(ctx context.Context) *ClusterUsageCSVParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cluster usage c s v params
func (o *ClusterUsageCSVParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cluster usage c s v params
func (o *ClusterUsageCSVParams) WithHTTPClient(client *http.Client) *ClusterUsageCSVParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cluster usage c s v params
func (o *ClusterUsageCSVParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the cluster usage c s v params
func (o *ClusterUsageCSVParams) WithBody(body *models.V1ClusterUsageRequest) *ClusterUsageCSVParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the cluster usage c s v params
func (o *ClusterUsageCSVParams) SetBody(body *models.V1ClusterUsageRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ClusterUsageCSVParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
