// Code generated by go-swagger; DO NOT EDIT.

package accounting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
)

// NewContainerUsageParams creates a new ContainerUsageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewContainerUsageParams() *ContainerUsageParams {
	return &ContainerUsageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewContainerUsageParamsWithTimeout creates a new ContainerUsageParams object
// with the ability to set a timeout on a request.
func NewContainerUsageParamsWithTimeout(timeout time.Duration) *ContainerUsageParams {
	return &ContainerUsageParams{
		timeout: timeout,
	}
}

// NewContainerUsageParamsWithContext creates a new ContainerUsageParams object
// with the ability to set a context for a request.
func NewContainerUsageParamsWithContext(ctx context.Context) *ContainerUsageParams {
	return &ContainerUsageParams{
		Context: ctx,
	}
}

// NewContainerUsageParamsWithHTTPClient creates a new ContainerUsageParams object
// with the ability to set a custom HTTPClient for a request.
func NewContainerUsageParamsWithHTTPClient(client *http.Client) *ContainerUsageParams {
	return &ContainerUsageParams{
		HTTPClient: client,
	}
}

/*
ContainerUsageParams contains all the parameters to send to the API endpoint

	for the container usage operation.

	Typically these are written to a http.Request.
*/
type ContainerUsageParams struct {

	// Body.
	Body *models.V1ContainerUsageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the container usage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContainerUsageParams) WithDefaults() *ContainerUsageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the container usage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContainerUsageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the container usage params
func (o *ContainerUsageParams) WithTimeout(timeout time.Duration) *ContainerUsageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the container usage params
func (o *ContainerUsageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the container usage params
func (o *ContainerUsageParams) WithContext(ctx context.Context) *ContainerUsageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the container usage params
func (o *ContainerUsageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the container usage params
func (o *ContainerUsageParams) WithHTTPClient(client *http.Client) *ContainerUsageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the container usage params
func (o *ContainerUsageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the container usage params
func (o *ContainerUsageParams) WithBody(body *models.V1ContainerUsageRequest) *ContainerUsageParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the container usage params
func (o *ContainerUsageParams) SetBody(body *models.V1ContainerUsageRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ContainerUsageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
