// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// ClientPostReader is a Reader for the ClientPost structure.
type ClientPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ClientPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewClientPostCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewClientPostDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewClientPostCreated creates a ClientPostCreated with default headers values
func NewClientPostCreated() *ClientPostCreated {
	return &ClientPostCreated{}
}

/* ClientPostCreated describes a response with status code 201, with default header values.

gateway client created
*/
type ClientPostCreated struct {
	Payload *models.V1GatewayClientResponse
}

func (o *ClientPostCreated) Error() string {
	return fmt.Sprintf("[POST /gateway/v1/projects/{projectuid}/clients][%d] clientPostCreated  %+v", 201, o.Payload)
}
func (o *ClientPostCreated) GetPayload() *models.V1GatewayClientResponse {
	return o.Payload
}

func (o *ClientPostCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GatewayClientResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewClientPostDefault creates a ClientPostDefault with default headers values
func NewClientPostDefault(code int) *ClientPostDefault {
	return &ClientPostDefault{
		_statusCode: code,
	}
}

/* ClientPostDefault describes a response with status code -1, with default header values.

error
*/
type ClientPostDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the client post default response
func (o *ClientPostDefault) Code() int {
	return o._statusCode
}

func (o *ClientPostDefault) Error() string {
	return fmt.Sprintf("[POST /gateway/v1/projects/{projectuid}/clients][%d] clientPost default  %+v", o._statusCode, o.Payload)
}
func (o *ClientPostDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *ClientPostDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
