// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// ClientPatchReader is a Reader for the ClientPatch structure.
type ClientPatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ClientPatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewClientPatchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewClientPatchDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewClientPatchOK creates a ClientPatchOK with default headers values
func NewClientPatchOK() *ClientPatchOK {
	return &ClientPatchOK{}
}

/* ClientPatchOK describes a response with status code 200, with default header values.

gateway pipes added to the gateway client(s)
*/
type ClientPatchOK struct {
	Payload *models.V1GatewayClientResponse
}

func (o *ClientPatchOK) Error() string {
	return fmt.Sprintf("[PATCH /gateway/v1/projects/{projectuid}/clients/{name}][%d] clientPatchOK  %+v", 200, o.Payload)
}
func (o *ClientPatchOK) GetPayload() *models.V1GatewayClientResponse {
	return o.Payload
}

func (o *ClientPatchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GatewayClientResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewClientPatchDefault creates a ClientPatchDefault with default headers values
func NewClientPatchDefault(code int) *ClientPatchDefault {
	return &ClientPatchDefault{
		_statusCode: code,
	}
}

/* ClientPatchDefault describes a response with status code -1, with default header values.

error
*/
type ClientPatchDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the client patch default response
func (o *ClientPatchDefault) Code() int {
	return o._statusCode
}

func (o *ClientPatchDefault) Error() string {
	return fmt.Sprintf("[PATCH /gateway/v1/projects/{projectuid}/clients/{name}][%d] clientPatch default  %+v", o._statusCode, o.Payload)
}
func (o *ClientPatchDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *ClientPatchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
