// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// ClientListReader is a Reader for the ClientList structure.
type ClientListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ClientListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewClientListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewClientListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewClientListOK creates a ClientListOK with default headers values
func NewClientListOK() *ClientListOK {
	return &ClientListOK{}
}

/* ClientListOK describes a response with status code 200, with default header values.

gateway clients fetched
*/
type ClientListOK struct {
	Payload []*models.V1GatewayClientResponse
}

func (o *ClientListOK) Error() string {
	return fmt.Sprintf("[GET /gateway/v1/projects/{projectuid}/clients][%d] clientListOK  %+v", 200, o.Payload)
}
func (o *ClientListOK) GetPayload() []*models.V1GatewayClientResponse {
	return o.Payload
}

func (o *ClientListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewClientListDefault creates a ClientListDefault with default headers values
func NewClientListDefault(code int) *ClientListDefault {
	return &ClientListDefault{
		_statusCode: code,
	}
}

/* ClientListDefault describes a response with status code -1, with default header values.

error
*/
type ClientListDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the client list default response
func (o *ClientListDefault) Code() int {
	return o._statusCode
}

func (o *ClientListDefault) Error() string {
	return fmt.Sprintf("[GET /gateway/v1/projects/{projectuid}/clients][%d] clientList default  %+v", o._statusCode, o.Payload)
}
func (o *ClientListDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *ClientListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
