// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
)

// NewClientPostParams creates a new ClientPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewClientPostParams() *ClientPostParams {
	return &ClientPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewClientPostParamsWithTimeout creates a new ClientPostParams object
// with the ability to set a timeout on a request.
func NewClientPostParamsWithTimeout(timeout time.Duration) *ClientPostParams {
	return &ClientPostParams{
		timeout: timeout,
	}
}

// NewClientPostParamsWithContext creates a new ClientPostParams object
// with the ability to set a context for a request.
func NewClientPostParamsWithContext(ctx context.Context) *ClientPostParams {
	return &ClientPostParams{
		Context: ctx,
	}
}

// NewClientPostParamsWithHTTPClient creates a new ClientPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewClientPostParamsWithHTTPClient(client *http.Client) *ClientPostParams {
	return &ClientPostParams{
		HTTPClient: client,
	}
}

/* ClientPostParams contains all the parameters to send to the API endpoint
   for the client post operation.

   Typically these are written to a http.Request.
*/
type ClientPostParams struct {

	// Body.
	Body *models.V1GatewayClientPostRequest

	/* Projectuid.

	   project UUID
	*/
	Projectuid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the client post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClientPostParams) WithDefaults() *ClientPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the client post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ClientPostParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the client post params
func (o *ClientPostParams) WithTimeout(timeout time.Duration) *ClientPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the client post params
func (o *ClientPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the client post params
func (o *ClientPostParams) WithContext(ctx context.Context) *ClientPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the client post params
func (o *ClientPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the client post params
func (o *ClientPostParams) WithHTTPClient(client *http.Client) *ClientPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the client post params
func (o *ClientPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the client post params
func (o *ClientPostParams) WithBody(body *models.V1GatewayClientPostRequest) *ClientPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the client post params
func (o *ClientPostParams) SetBody(body *models.V1GatewayClientPostRequest) {
	o.Body = body
}

// WithProjectuid adds the projectuid to the client post params
func (o *ClientPostParams) WithProjectuid(projectuid string) *ClientPostParams {
	o.SetProjectuid(projectuid)
	return o
}

// SetProjectuid adds the projectuid to the client post params
func (o *ClientPostParams) SetProjectuid(projectuid string) {
	o.Projectuid = projectuid
}

// WriteToRequest writes these params to a swagger request
func (o *ClientPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param projectuid
	if err := r.SetPathParam("projectuid", o.Projectuid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
