// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// CreateClientReader is a Reader for the CreateClient structure.
type CreateClientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateClientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateClientCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateClientDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateClientCreated creates a CreateClientCreated with default headers values
func NewCreateClientCreated() *CreateClientCreated {
	return &CreateClientCreated{}
}

/* CreateClientCreated describes a response with status code 201, with default header values.

gateway client created
*/
type CreateClientCreated struct {
	Payload *models.V1GatewayInstanceResponse
}

func (o *CreateClientCreated) Error() string {
	return fmt.Sprintf("[POST /v1/gateway/client][%d] createClientCreated  %+v", 201, o.Payload)
}
func (o *CreateClientCreated) GetPayload() *models.V1GatewayInstanceResponse {
	return o.Payload
}

func (o *CreateClientCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GatewayInstanceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClientDefault creates a CreateClientDefault with default headers values
func NewCreateClientDefault(code int) *CreateClientDefault {
	return &CreateClientDefault{
		_statusCode: code,
	}
}

/* CreateClientDefault describes a response with status code -1, with default header values.

error
*/
type CreateClientDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the create client default response
func (o *CreateClientDefault) Code() int {
	return o._statusCode
}

func (o *CreateClientDefault) Error() string {
	return fmt.Sprintf("[POST /v1/gateway/client][%d] createClient default  %+v", o._statusCode, o.Payload)
}
func (o *CreateClientDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *CreateClientDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
