// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// DeleteClientReader is a Reader for the DeleteClient structure.
type DeleteClientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteClientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteClientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteClientDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteClientOK creates a DeleteClientOK with default headers values
func NewDeleteClientOK() *DeleteClientOK {
	return &DeleteClientOK{}
}

/* DeleteClientOK describes a response with status code 200, with default header values.

gateway client deleted
*/
type DeleteClientOK struct {
	Payload *models.V1GatewayInstanceResponse
}

func (o *DeleteClientOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/gateway/client][%d] deleteClientOK  %+v", 200, o.Payload)
}
func (o *DeleteClientOK) GetPayload() *models.V1GatewayInstanceResponse {
	return o.Payload
}

func (o *DeleteClientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GatewayInstanceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteClientDefault creates a DeleteClientDefault with default headers values
func NewDeleteClientDefault(code int) *DeleteClientDefault {
	return &DeleteClientDefault{
		_statusCode: code,
	}
}

/* DeleteClientDefault describes a response with status code -1, with default header values.

error
*/
type DeleteClientDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the delete client default response
func (o *DeleteClientDefault) Code() int {
	return o._statusCode
}

func (o *DeleteClientDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/gateway/client][%d] deleteClient default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteClientDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *DeleteClientDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
