// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new gateway API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for gateway API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	HandleCreateRequest(params *HandleCreateRequestParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HandleCreateRequestCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  HandleCreateRequest handle create request API
*/
func (a *Client) HandleCreateRequest(params *HandleCreateRequestParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HandleCreateRequestCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHandleCreateRequestParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "handleCreateRequest",
		Method:             "POST",
		PathPattern:        "/v1/gateway",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &HandleCreateRequestReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HandleCreateRequestCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*HandleCreateRequestDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
