// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// GetClientReader is a Reader for the GetClient structure.
type GetClientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetClientDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetClientOK creates a GetClientOK with default headers values
func NewGetClientOK() *GetClientOK {
	return &GetClientOK{}
}

/* GetClientOK describes a response with status code 200, with default header values.

gateway client fetched
*/
type GetClientOK struct {
	Payload *models.V1GatewayClientDescribeResponse
}

func (o *GetClientOK) Error() string {
	return fmt.Sprintf("[GET /gateway/v1/projects/{projectuid}/clients/{name}][%d] getClientOK  %+v", 200, o.Payload)
}
func (o *GetClientOK) GetPayload() *models.V1GatewayClientDescribeResponse {
	return o.Payload
}

func (o *GetClientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GatewayClientDescribeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClientDefault creates a GetClientDefault with default headers values
func NewGetClientDefault(code int) *GetClientDefault {
	return &GetClientDefault{
		_statusCode: code,
	}
}

/* GetClientDefault describes a response with status code -1, with default header values.

error
*/
type GetClientDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the get client default response
func (o *GetClientDefault) Code() int {
	return o._statusCode
}

func (o *GetClientDefault) Error() string {
	return fmt.Sprintf("[GET /gateway/v1/projects/{projectuid}/clients/{name}][%d] getClient default  %+v", o._statusCode, o.Payload)
}
func (o *GetClientDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *GetClientDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
