// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// GetServerReader is a Reader for the GetServer structure.
type GetServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetServerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetServerOK creates a GetServerOK with default headers values
func NewGetServerOK() *GetServerOK {
	return &GetServerOK{}
}

/* GetServerOK describes a response with status code 200, with default header values.

gateway server fetched
*/
type GetServerOK struct {
	Payload *models.V1GatewayInstanceResponse
}

func (o *GetServerOK) Error() string {
	return fmt.Sprintf("[GET /gateway/v1/projects/{projectuid}/servers/{name}][%d] getServerOK  %+v", 200, o.Payload)
}
func (o *GetServerOK) GetPayload() *models.V1GatewayInstanceResponse {
	return o.Payload
}

func (o *GetServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GatewayInstanceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServerDefault creates a GetServerDefault with default headers values
func NewGetServerDefault(code int) *GetServerDefault {
	return &GetServerDefault{
		_statusCode: code,
	}
}

/* GetServerDefault describes a response with status code -1, with default header values.

error
*/
type GetServerDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the get server default response
func (o *GetServerDefault) Code() int {
	return o._statusCode
}

func (o *GetServerDefault) Error() string {
	return fmt.Sprintf("[GET /gateway/v1/projects/{projectuid}/servers/{name}][%d] getServer default  %+v", o._statusCode, o.Payload)
}
func (o *GetServerDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *GetServerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
