// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// PatchClientReader is a Reader for the PatchClient structure.
type PatchClientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchClientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchClientOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPatchClientDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPatchClientOK creates a PatchClientOK with default headers values
func NewPatchClientOK() *PatchClientOK {
	return &PatchClientOK{}
}

/* PatchClientOK describes a response with status code 200, with default header values.

gateway pipes added to the gateway client(s)
*/
type PatchClientOK struct {
	Payload *models.V1GatewayInstanceResponse
}

func (o *PatchClientOK) Error() string {
	return fmt.Sprintf("[PATCH /gateway/v1/projects/{projectuid}/clients/{name}][%d] patchClientOK  %+v", 200, o.Payload)
}
func (o *PatchClientOK) GetPayload() *models.V1GatewayInstanceResponse {
	return o.Payload
}

func (o *PatchClientOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GatewayInstanceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchClientDefault creates a PatchClientDefault with default headers values
func NewPatchClientDefault(code int) *PatchClientDefault {
	return &PatchClientDefault{
		_statusCode: code,
	}
}

/* PatchClientDefault describes a response with status code -1, with default header values.

error
*/
type PatchClientDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// Code gets the status code for the patch client default response
func (o *PatchClientDefault) Code() int {
	return o._statusCode
}

func (o *PatchClientDefault) Error() string {
	return fmt.Sprintf("[PATCH /gateway/v1/projects/{projectuid}/clients/{name}][%d] patchClient default  %+v", o._statusCode, o.Payload)
}
func (o *PatchClientDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *PatchClientDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
