// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
)

// NewPostClientParams creates a new PostClientParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostClientParams() *PostClientParams {
	return &PostClientParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostClientParamsWithTimeout creates a new PostClientParams object
// with the ability to set a timeout on a request.
func NewPostClientParamsWithTimeout(timeout time.Duration) *PostClientParams {
	return &PostClientParams{
		timeout: timeout,
	}
}

// NewPostClientParamsWithContext creates a new PostClientParams object
// with the ability to set a context for a request.
func NewPostClientParamsWithContext(ctx context.Context) *PostClientParams {
	return &PostClientParams{
		Context: ctx,
	}
}

// NewPostClientParamsWithHTTPClient creates a new PostClientParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostClientParamsWithHTTPClient(client *http.Client) *PostClientParams {
	return &PostClientParams{
		HTTPClient: client,
	}
}

/* PostClientParams contains all the parameters to send to the API endpoint
   for the post client operation.

   Typically these are written to a http.Request.
*/
type PostClientParams struct {

	// Body.
	Body *models.V1GatewayClientPostRequest

	/* Projectuid.

	   project UUID
	*/
	Projectuid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post client params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostClientParams) WithDefaults() *PostClientParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post client params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostClientParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post client params
func (o *PostClientParams) WithTimeout(timeout time.Duration) *PostClientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post client params
func (o *PostClientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post client params
func (o *PostClientParams) WithContext(ctx context.Context) *PostClientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post client params
func (o *PostClientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post client params
func (o *PostClientParams) WithHTTPClient(client *http.Client) *PostClientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post client params
func (o *PostClientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post client params
func (o *PostClientParams) WithBody(body *models.V1GatewayClientPostRequest) *PostClientParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post client params
func (o *PostClientParams) SetBody(body *models.V1GatewayClientPostRequest) {
	o.Body = body
}

// WithProjectuid adds the projectuid to the post client params
func (o *PostClientParams) WithProjectuid(projectuid string) *PostClientParams {
	o.SetProjectuid(projectuid)
	return o
}

// SetProjectuid adds the projectuid to the post client params
func (o *PostClientParams) SetProjectuid(projectuid string) {
	o.Projectuid = projectuid
}

// WriteToRequest writes these params to a swagger request
func (o *PostClientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param projectuid
	if err := r.SetPathParam("projectuid", o.Projectuid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
