// Code generated by go-swagger; DO NOT EDIT.

package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// FindSnapshotsReader is a Reader for the FindSnapshots structure.
type FindSnapshotsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindSnapshotsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindSnapshotsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFindSnapshotsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFindSnapshotsOK creates a FindSnapshotsOK with default headers values
func NewFindSnapshotsOK() *FindSnapshotsOK {
	return &FindSnapshotsOK{}
}

/*
FindSnapshotsOK describes a response with status code 200, with default header values.

OK
*/
type FindSnapshotsOK struct {
	Payload []*models.V1SnapshotResponse
}

// IsSuccess returns true when this find snapshots o k response has a 2xx status code
func (o *FindSnapshotsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find snapshots o k response has a 3xx status code
func (o *FindSnapshotsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find snapshots o k response has a 4xx status code
func (o *FindSnapshotsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find snapshots o k response has a 5xx status code
func (o *FindSnapshotsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find snapshots o k response a status code equal to that given
func (o *FindSnapshotsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find snapshots o k response
func (o *FindSnapshotsOK) Code() int {
	return 200
}

func (o *FindSnapshotsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/volume/snapshot/find][%d] findSnapshotsOK %s", 200, payload)
}

func (o *FindSnapshotsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/volume/snapshot/find][%d] findSnapshotsOK %s", 200, payload)
}

func (o *FindSnapshotsOK) GetPayload() []*models.V1SnapshotResponse {
	return o.Payload
}

func (o *FindSnapshotsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindSnapshotsDefault creates a FindSnapshotsDefault with default headers values
func NewFindSnapshotsDefault(code int) *FindSnapshotsDefault {
	return &FindSnapshotsDefault{
		_statusCode: code,
	}
}

/*
FindSnapshotsDefault describes a response with status code -1, with default header values.

Error
*/
type FindSnapshotsDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// IsSuccess returns true when this find snapshots default response has a 2xx status code
func (o *FindSnapshotsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this find snapshots default response has a 3xx status code
func (o *FindSnapshotsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this find snapshots default response has a 4xx status code
func (o *FindSnapshotsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this find snapshots default response has a 5xx status code
func (o *FindSnapshotsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this find snapshots default response a status code equal to that given
func (o *FindSnapshotsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the find snapshots default response
func (o *FindSnapshotsDefault) Code() int {
	return o._statusCode
}

func (o *FindSnapshotsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/volume/snapshot/find][%d] findSnapshots default %s", o._statusCode, payload)
}

func (o *FindSnapshotsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/volume/snapshot/find][%d] findSnapshots default %s", o._statusCode, payload)
}

func (o *FindSnapshotsDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *FindSnapshotsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
