// Code generated by go-swagger; DO NOT EDIT.

package volume

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fi-ts/cloud-go/api/models"
	"github.com/metal-stack/metal-lib/httperrors"
)

// SetVolumeQoSPolicyReader is a Reader for the SetVolumeQoSPolicy structure.
type SetVolumeQoSPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetVolumeQoSPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetVolumeQoSPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSetVolumeQoSPolicyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSetVolumeQoSPolicyOK creates a SetVolumeQoSPolicyOK with default headers values
func NewSetVolumeQoSPolicyOK() *SetVolumeQoSPolicyOK {
	return &SetVolumeQoSPolicyOK{}
}

/*
SetVolumeQoSPolicyOK describes a response with status code 200, with default header values.

OK
*/
type SetVolumeQoSPolicyOK struct {
	Payload []*models.V1VolumeResponse
}

// IsSuccess returns true when this set volume qo s policy o k response has a 2xx status code
func (o *SetVolumeQoSPolicyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this set volume qo s policy o k response has a 3xx status code
func (o *SetVolumeQoSPolicyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this set volume qo s policy o k response has a 4xx status code
func (o *SetVolumeQoSPolicyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this set volume qo s policy o k response has a 5xx status code
func (o *SetVolumeQoSPolicyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this set volume qo s policy o k response a status code equal to that given
func (o *SetVolumeQoSPolicyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the set volume qo s policy o k response
func (o *SetVolumeQoSPolicyOK) Code() int {
	return 200
}

func (o *SetVolumeQoSPolicyOK) Error() string {
	return fmt.Sprintf("[POST /v1/volume/{id}/qos][%d] setVolumeQoSPolicyOK  %+v", 200, o.Payload)
}

func (o *SetVolumeQoSPolicyOK) String() string {
	return fmt.Sprintf("[POST /v1/volume/{id}/qos][%d] setVolumeQoSPolicyOK  %+v", 200, o.Payload)
}

func (o *SetVolumeQoSPolicyOK) GetPayload() []*models.V1VolumeResponse {
	return o.Payload
}

func (o *SetVolumeQoSPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetVolumeQoSPolicyDefault creates a SetVolumeQoSPolicyDefault with default headers values
func NewSetVolumeQoSPolicyDefault(code int) *SetVolumeQoSPolicyDefault {
	return &SetVolumeQoSPolicyDefault{
		_statusCode: code,
	}
}

/*
SetVolumeQoSPolicyDefault describes a response with status code -1, with default header values.

Error
*/
type SetVolumeQoSPolicyDefault struct {
	_statusCode int

	Payload *httperrors.HTTPErrorResponse
}

// IsSuccess returns true when this set volume qo s policy default response has a 2xx status code
func (o *SetVolumeQoSPolicyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this set volume qo s policy default response has a 3xx status code
func (o *SetVolumeQoSPolicyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this set volume qo s policy default response has a 4xx status code
func (o *SetVolumeQoSPolicyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this set volume qo s policy default response has a 5xx status code
func (o *SetVolumeQoSPolicyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this set volume qo s policy default response a status code equal to that given
func (o *SetVolumeQoSPolicyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the set volume qo s policy default response
func (o *SetVolumeQoSPolicyDefault) Code() int {
	return o._statusCode
}

func (o *SetVolumeQoSPolicyDefault) Error() string {
	return fmt.Sprintf("[POST /v1/volume/{id}/qos][%d] setVolumeQoSPolicy default  %+v", o._statusCode, o.Payload)
}

func (o *SetVolumeQoSPolicyDefault) String() string {
	return fmt.Sprintf("[POST /v1/volume/{id}/qos][%d] setVolumeQoSPolicy default  %+v", o._statusCode, o.Payload)
}

func (o *SetVolumeQoSPolicyDefault) GetPayload() *httperrors.HTTPErrorResponse {
	return o.Payload
}

func (o *SetVolumeQoSPolicyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(httperrors.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
