// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1AuditBackendS3 v1 audit backend s3
//
// swagger:model v1.AuditBackendS3
type V1AuditBackendS3 struct {

	// access key
	// Required: true
	AccessKey *string `json:"accessKey"`

	// bucket
	// Required: true
	Bucket *string `json:"bucket"`

	// enabled
	// Required: true
	Enabled *bool `json:"enabled"`

	// endpoint
	// Required: true
	Endpoint *string `json:"endpoint"`

	// prefix
	Prefix string `json:"prefix,omitempty"`

	// region
	// Required: true
	Region *string `json:"region"`

	// s3 key format
	// Required: true
	S3KeyFormat *string `json:"s3KeyFormat"`

	// secret key
	// Required: true
	SecretKey *string `json:"secretKey"`

	// tls enabled
	// Required: true
	TLSEnabled *bool `json:"tlsEnabled"`

	// total file size
	// Required: true
	TotalFileSize *string `json:"totalFileSize"`

	// upload timeout
	// Required: true
	UploadTimeout *string `json:"uploadTimeout"`

	// use compression
	// Required: true
	UseCompression *bool `json:"useCompression"`
}

// Validate validates this v1 audit backend s3
func (m *V1AuditBackendS3) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBucket(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEndpoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateS3KeyFormat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecretKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTLSEnabled(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalFileSize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUploadTimeout(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUseCompression(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1AuditBackendS3) validateAccessKey(formats strfmt.Registry) error {

	if err := validate.Required("accessKey", "body", m.AccessKey); err != nil {
		return err
	}

	return nil
}

func (m *V1AuditBackendS3) validateBucket(formats strfmt.Registry) error {

	if err := validate.Required("bucket", "body", m.Bucket); err != nil {
		return err
	}

	return nil
}

func (m *V1AuditBackendS3) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("enabled", "body", m.Enabled); err != nil {
		return err
	}

	return nil
}

func (m *V1AuditBackendS3) validateEndpoint(formats strfmt.Registry) error {

	if err := validate.Required("endpoint", "body", m.Endpoint); err != nil {
		return err
	}

	return nil
}

func (m *V1AuditBackendS3) validateRegion(formats strfmt.Registry) error {

	if err := validate.Required("region", "body", m.Region); err != nil {
		return err
	}

	return nil
}

func (m *V1AuditBackendS3) validateS3KeyFormat(formats strfmt.Registry) error {

	if err := validate.Required("s3KeyFormat", "body", m.S3KeyFormat); err != nil {
		return err
	}

	return nil
}

func (m *V1AuditBackendS3) validateSecretKey(formats strfmt.Registry) error {

	if err := validate.Required("secretKey", "body", m.SecretKey); err != nil {
		return err
	}

	return nil
}

func (m *V1AuditBackendS3) validateTLSEnabled(formats strfmt.Registry) error {

	if err := validate.Required("tlsEnabled", "body", m.TLSEnabled); err != nil {
		return err
	}

	return nil
}

func (m *V1AuditBackendS3) validateTotalFileSize(formats strfmt.Registry) error {

	if err := validate.Required("totalFileSize", "body", m.TotalFileSize); err != nil {
		return err
	}

	return nil
}

func (m *V1AuditBackendS3) validateUploadTimeout(formats strfmt.Registry) error {

	if err := validate.Required("uploadTimeout", "body", m.UploadTimeout); err != nil {
		return err
	}

	return nil
}

func (m *V1AuditBackendS3) validateUseCompression(formats strfmt.Registry) error {

	if err := validate.Required("useCompression", "body", m.UseCompression); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 audit backend s3 based on context it is used
func (m *V1AuditBackendS3) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1AuditBackendS3) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1AuditBackendS3) UnmarshalBinary(b []byte) error {
	var res V1AuditBackendS3
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
