// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Clone v1 clone
//
// swagger:model v1.Clone
type V1Clone struct {

	// cluster
	Cluster string `json:"cluster,omitempty"`

	// s3 access key
	S3AccessKey string `json:"s3AccessKey,omitempty"`

	// s3 endpoint
	S3Endpoint string `json:"s3Endpoint,omitempty"`

	// timestamp
	Timestamp string `json:"timestamp,omitempty"`
}

// Validate validates this v1 clone
func (m *V1Clone) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 clone based on context it is used
func (m *V1Clone) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1Clone) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Clone) UnmarshalBinary(b []byte) error {
	var res V1Clone
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
