// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1PostgresVersion v1 postgres version
//
// swagger:model v1.PostgresVersion
type V1PostgresVersion struct {

	// expiration date
	// Required: true
	// Format: date-time
	ExpirationDate *strfmt.DateTime `json:"ExpirationDate"`

	// version
	// Required: true
	Version *string `json:"Version"`
}

// Validate validates this v1 postgres version
func (m *V1PostgresVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpirationDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1PostgresVersion) validateExpirationDate(formats strfmt.Registry) error {

	if err := validate.Required("ExpirationDate", "body", m.ExpirationDate); err != nil {
		return err
	}

	if err := validate.FormatOf("ExpirationDate", "body", "date-time", m.ExpirationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *V1PostgresVersion) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("Version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 postgres version based on context it is used
func (m *V1PostgresVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1PostgresVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1PostgresVersion) UnmarshalBinary(b []byte) error {
	var res V1PostgresVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
