// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1PostgresBackupConfigUpdateRequest v1 postgres backup config update request
//
// swagger:model v1.PostgresBackupConfigUpdateRequest
type V1PostgresBackupConfigUpdateRequest struct {

	// id
	ID string `json:"id,omitempty"`

	// retention
	Retention int32 `json:"retention,omitempty"`

	// schedule
	Schedule string `json:"schedule,omitempty"`
}

// Validate validates this v1 postgres backup config update request
func (m *V1PostgresBackupConfigUpdateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 postgres backup config update request based on context it is used
func (m *V1PostgresBackupConfigUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1PostgresBackupConfigUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1PostgresBackupConfigUpdateRequest) UnmarshalBinary(b []byte) error {
	var res V1PostgresBackupConfigUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
