// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1PostgresLimits v1 postgres limits
//
// swagger:model v1.PostgresLimits
type V1PostgresLimits struct {

	// cpu max
	// Required: true
	CPUMax *string `json:"cpuMax"`

	// cpu min
	// Required: true
	CPUMin *string `json:"cpuMin"`

	// instances max
	// Required: true
	InstancesMax *int64 `json:"instancesMax"`

	// memoryfactor max
	// Required: true
	MemoryfactorMax *int64 `json:"memoryfactorMax"`

	// memoryfactor min
	// Required: true
	MemoryfactorMin *int64 `json:"memoryfactorMin"`

	// storage size max
	// Required: true
	StorageSizeMax *string `json:"storageSizeMax"`

	// storage size min
	// Required: true
	StorageSizeMin *string `json:"storageSizeMin"`
}

// Validate validates this v1 postgres limits
func (m *V1PostgresLimits) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCPUMax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCPUMin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstancesMax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMemoryfactorMax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMemoryfactorMin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStorageSizeMax(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStorageSizeMin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1PostgresLimits) validateCPUMax(formats strfmt.Registry) error {

	if err := validate.Required("cpuMax", "body", m.CPUMax); err != nil {
		return err
	}

	return nil
}

func (m *V1PostgresLimits) validateCPUMin(formats strfmt.Registry) error {

	if err := validate.Required("cpuMin", "body", m.CPUMin); err != nil {
		return err
	}

	return nil
}

func (m *V1PostgresLimits) validateInstancesMax(formats strfmt.Registry) error {

	if err := validate.Required("instancesMax", "body", m.InstancesMax); err != nil {
		return err
	}

	return nil
}

func (m *V1PostgresLimits) validateMemoryfactorMax(formats strfmt.Registry) error {

	if err := validate.Required("memoryfactorMax", "body", m.MemoryfactorMax); err != nil {
		return err
	}

	return nil
}

func (m *V1PostgresLimits) validateMemoryfactorMin(formats strfmt.Registry) error {

	if err := validate.Required("memoryfactorMin", "body", m.MemoryfactorMin); err != nil {
		return err
	}

	return nil
}

func (m *V1PostgresLimits) validateStorageSizeMax(formats strfmt.Registry) error {

	if err := validate.Required("storageSizeMax", "body", m.StorageSizeMax); err != nil {
		return err
	}

	return nil
}

func (m *V1PostgresLimits) validateStorageSizeMin(formats strfmt.Registry) error {

	if err := validate.Required("storageSizeMin", "body", m.StorageSizeMin); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 postgres limits based on context it is used
func (m *V1PostgresLimits) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1PostgresLimits) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1PostgresLimits) UnmarshalBinary(b []byte) error {
	var res V1PostgresLimits
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
