// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1SnapshotFindRequest v1 snapshot find request
//
// swagger:model v1.SnapshotFindRequest
type V1SnapshotFindRequest struct {

	// partition ID
	// Required: true
	PartitionID *string `json:"PartitionID"`

	// project ID
	// Required: true
	ProjectID *string `json:"ProjectID"`

	// snapshot ID
	// Required: true
	SnapshotID *string `json:"SnapshotID"`

	// tenant ID
	// Required: true
	TenantID *string `json:"TenantID"`
}

// Validate validates this v1 snapshot find request
func (m *V1SnapshotFindRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePartitionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProjectID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSnapshotID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTenantID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SnapshotFindRequest) validatePartitionID(formats strfmt.Registry) error {

	if err := validate.Required("PartitionID", "body", m.PartitionID); err != nil {
		return err
	}

	return nil
}

func (m *V1SnapshotFindRequest) validateProjectID(formats strfmt.Registry) error {

	if err := validate.Required("ProjectID", "body", m.ProjectID); err != nil {
		return err
	}

	return nil
}

func (m *V1SnapshotFindRequest) validateSnapshotID(formats strfmt.Registry) error {

	if err := validate.Required("SnapshotID", "body", m.SnapshotID); err != nil {
		return err
	}

	return nil
}

func (m *V1SnapshotFindRequest) validateTenantID(formats strfmt.Registry) error {

	if err := validate.Required("TenantID", "body", m.TenantID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 snapshot find request based on context it is used
func (m *V1SnapshotFindRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1SnapshotFindRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SnapshotFindRequest) UnmarshalBinary(b []byte) error {
	var res V1SnapshotFindRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
