// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1SystemComponents v1 system components
//
// swagger:model v1.SystemComponents
type V1SystemComponents struct {

	// node local DNS
	// Required: true
	NodeLocalDNS *V1NodeLocalDNS `json:"NodeLocalDNS"`
}

// Validate validates this v1 system components
func (m *V1SystemComponents) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNodeLocalDNS(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SystemComponents) validateNodeLocalDNS(formats strfmt.Registry) error {

	if err := validate.Required("NodeLocalDNS", "body", m.NodeLocalDNS); err != nil {
		return err
	}

	if m.NodeLocalDNS != nil {
		if err := m.NodeLocalDNS.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("NodeLocalDNS")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("NodeLocalDNS")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 system components based on the context it is used
func (m *V1SystemComponents) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNodeLocalDNS(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SystemComponents) contextValidateNodeLocalDNS(ctx context.Context, formats strfmt.Registry) error {

	if m.NodeLocalDNS != nil {

		if err := m.NodeLocalDNS.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("NodeLocalDNS")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("NodeLocalDNS")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1SystemComponents) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SystemComponents) UnmarshalBinary(b []byte) error {
	var res V1SystemComponents
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
