// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1alpha1IPV4Pool v1alpha1 ipv4 pool
// swagger:model v1alpha1.IPv4Pool
type V1alpha1IPV4Pool interface{}
