// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// V1alpha1AuditPolicy v1alpha1 audit policy
// swagger:model v1alpha1.AuditPolicy
type V1alpha1AuditPolicy struct {

	// config map ref
	ConfigMapRef *V1ObjectReference `json:"configMapRef,omitempty"`
}

// Validate validates this v1alpha1 audit policy
func (m *V1alpha1AuditPolicy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfigMapRef(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1AuditPolicy) validateConfigMapRef(formats strfmt.Registry) error {

	if swag.IsZero(m.ConfigMapRef) { // not required
		return nil
	}

	if m.ConfigMapRef != nil {
		if err := m.ConfigMapRef.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("configMapRef")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1AuditPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1AuditPolicy) UnmarshalBinary(b []byte) error {
	var res V1alpha1AuditPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
