// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// V1alpha1Addons v1alpha1 addons
// swagger:model v1alpha1.Addons
type V1alpha1Addons struct {

	// kubernetes dashboard
	KubernetesDashboard *V1alpha1KubernetesDashboard `json:"kubernetes-dashboard,omitempty"`

	// nginx ingress
	NginxIngress *V1alpha1NginxIngress `json:"nginx-ingress,omitempty"`
}

// Validate validates this v1alpha1 addons
func (m *V1alpha1Addons) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKubernetesDashboard(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNginxIngress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1Addons) validateKubernetesDashboard(formats strfmt.Registry) error {

	if swag.IsZero(m.KubernetesDashboard) { // not required
		return nil
	}

	if m.KubernetesDashboard != nil {
		if err := m.KubernetesDashboard.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("kubernetes-dashboard")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1Addons) validateNginxIngress(formats strfmt.Registry) error {

	if swag.IsZero(m.NginxIngress) { // not required
		return nil
	}

	if m.NginxIngress != nil {
		if err := m.NginxIngress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("nginx-ingress")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1Addons) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1Addons) UnmarshalBinary(b []byte) error {
	var res V1alpha1Addons
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
