// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// V1alpha1WorkerKubernetes v1alpha1 worker kubernetes
// swagger:model v1alpha1.WorkerKubernetes
type V1alpha1WorkerKubernetes struct {

	// kubelet
	Kubelet *V1alpha1KubeletConfig `json:"kubelet,omitempty"`
}

// Validate validates this v1alpha1 worker kubernetes
func (m *V1alpha1WorkerKubernetes) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKubelet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1WorkerKubernetes) validateKubelet(formats strfmt.Registry) error {

	if swag.IsZero(m.Kubelet) { // not required
		return nil
	}

	if m.Kubelet != nil {
		if err := m.Kubelet.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("kubelet")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1WorkerKubernetes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1WorkerKubernetes) UnmarshalBinary(b []byte) error {
	var res V1alpha1WorkerKubernetes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
