// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V1alpha1HorizontalPodAutoscalerConfig v1alpha1 horizontal pod autoscaler config
// swagger:model v1alpha1.HorizontalPodAutoscalerConfig
type V1alpha1HorizontalPodAutoscalerConfig struct {

	// cpu initialization period
	CPUInitializationPeriod string `json:"cpuInitializationPeriod,omitempty"`

	// downscale delay
	DownscaleDelay string `json:"downscaleDelay,omitempty"`

	// downscale stabilization
	DownscaleStabilization string `json:"downscaleStabilization,omitempty"`

	// initial readiness delay
	InitialReadinessDelay string `json:"initialReadinessDelay,omitempty"`

	// sync period
	SyncPeriod string `json:"syncPeriod,omitempty"`

	// tolerance
	Tolerance float64 `json:"tolerance,omitempty"`

	// upscale delay
	UpscaleDelay string `json:"upscaleDelay,omitempty"`
}

// Validate validates this v1alpha1 horizontal pod autoscaler config
func (m *V1alpha1HorizontalPodAutoscalerConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1HorizontalPodAutoscalerConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1HorizontalPodAutoscalerConfig) UnmarshalBinary(b []byte) error {
	var res V1alpha1HorizontalPodAutoscalerConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
