// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1alpha1NginxIngress v1alpha1 nginx ingress
// swagger:model v1alpha1.NginxIngress
type V1alpha1NginxIngress struct {

	// config
	Config map[string]string `json:"config,omitempty"`

	// enabled
	// Required: true
	Enabled *bool `json:"enabled"`

	// load balancer source ranges
	LoadBalancerSourceRanges []string `json:"loadBalancerSourceRanges"`
}

// Validate validates this v1alpha1 nginx ingress
func (m *V1alpha1NginxIngress) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnabled(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1NginxIngress) validateEnabled(formats strfmt.Registry) error {

	if err := validate.Required("enabled", "body", m.Enabled); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1NginxIngress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1NginxIngress) UnmarshalBinary(b []byte) error {
	var res V1alpha1NginxIngress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
