// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1alpha1IPV4PoolMode v1alpha1 ipv4 pool mode
// swagger:model v1alpha1.IPv4PoolMode
type V1alpha1IPV4PoolMode interface{}
