// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// V1beta1OIDCConfig v1beta1 o ID c config
// swagger:model v1beta1.OIDCConfig
type V1beta1OIDCConfig struct {

	// ca bundle
	CaBundle string `json:"caBundle,omitempty"`

	// client authentication
	ClientAuthentication *V1beta1OpenIDConnectClientAuthentication `json:"clientAuthentication,omitempty"`

	// client ID
	ClientID string `json:"clientID,omitempty"`

	// groups claim
	GroupsClaim string `json:"groupsClaim,omitempty"`

	// groups prefix
	GroupsPrefix string `json:"groupsPrefix,omitempty"`

	// issuer URL
	IssuerURL string `json:"issuerURL,omitempty"`

	// required claims
	RequiredClaims map[string]string `json:"requiredClaims,omitempty"`

	// signing algs
	SigningAlgs []string `json:"signingAlgs"`

	// username claim
	UsernameClaim string `json:"usernameClaim,omitempty"`

	// username prefix
	UsernamePrefix string `json:"usernamePrefix,omitempty"`
}

// Validate validates this v1beta1 o ID c config
func (m *V1beta1OIDCConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientAuthentication(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1OIDCConfig) validateClientAuthentication(formats strfmt.Registry) error {

	if swag.IsZero(m.ClientAuthentication) { // not required
		return nil
	}

	if m.ClientAuthentication != nil {
		if err := m.ClientAuthentication.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("clientAuthentication")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1OIDCConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1OIDCConfig) UnmarshalBinary(b []byte) error {
	var res V1beta1OIDCConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
