// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1beta1ShootStatus v1beta1 shoot status
// swagger:model v1beta1.ShootStatus
type V1beta1ShootStatus struct {

	// cluster identity
	ClusterIdentity string `json:"clusterIdentity,omitempty"`

	// conditions
	Conditions []*V1beta1Condition `json:"conditions"`

	// constraints
	Constraints []*V1beta1Condition `json:"constraints"`

	// gardener
	// Required: true
	Gardener *V1beta1Gardener `json:"gardener"`

	// hibernated
	// Required: true
	Hibernated *bool `json:"hibernated"`

	// last errors
	LastErrors []*V1beta1LastError `json:"lastErrors"`

	// last operation
	LastOperation *V1beta1LastOperation `json:"lastOperation,omitempty"`

	// observed generation
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// retry cycle start time
	RetryCycleStartTime string `json:"retryCycleStartTime,omitempty"`

	// seed name
	SeedName string `json:"seedName,omitempty"`

	// technical ID
	// Required: true
	TechnicalID *string `json:"technicalID"`

	// uid
	// Required: true
	UID *string `json:"uid"`
}

// Validate validates this v1beta1 shoot status
func (m *V1beta1ShootStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConditions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConstraints(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGardener(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHibernated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastOperation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTechnicalID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1ShootStatus) validateConditions(formats strfmt.Registry) error {

	if swag.IsZero(m.Conditions) { // not required
		return nil
	}

	for i := 0; i < len(m.Conditions); i++ {
		if swag.IsZero(m.Conditions[i]) { // not required
			continue
		}

		if m.Conditions[i] != nil {
			if err := m.Conditions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("conditions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1beta1ShootStatus) validateConstraints(formats strfmt.Registry) error {

	if swag.IsZero(m.Constraints) { // not required
		return nil
	}

	for i := 0; i < len(m.Constraints); i++ {
		if swag.IsZero(m.Constraints[i]) { // not required
			continue
		}

		if m.Constraints[i] != nil {
			if err := m.Constraints[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("constraints" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1beta1ShootStatus) validateGardener(formats strfmt.Registry) error {

	if err := validate.Required("gardener", "body", m.Gardener); err != nil {
		return err
	}

	if m.Gardener != nil {
		if err := m.Gardener.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gardener")
			}
			return err
		}
	}

	return nil
}

func (m *V1beta1ShootStatus) validateHibernated(formats strfmt.Registry) error {

	if err := validate.Required("hibernated", "body", m.Hibernated); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1ShootStatus) validateLastErrors(formats strfmt.Registry) error {

	if swag.IsZero(m.LastErrors) { // not required
		return nil
	}

	for i := 0; i < len(m.LastErrors); i++ {
		if swag.IsZero(m.LastErrors[i]) { // not required
			continue
		}

		if m.LastErrors[i] != nil {
			if err := m.LastErrors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("lastErrors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1beta1ShootStatus) validateLastOperation(formats strfmt.Registry) error {

	if swag.IsZero(m.LastOperation) { // not required
		return nil
	}

	if m.LastOperation != nil {
		if err := m.LastOperation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("lastOperation")
			}
			return err
		}
	}

	return nil
}

func (m *V1beta1ShootStatus) validateTechnicalID(formats strfmt.Registry) error {

	if err := validate.Required("technicalID", "body", m.TechnicalID); err != nil {
		return err
	}

	return nil
}

func (m *V1beta1ShootStatus) validateUID(formats strfmt.Registry) error {

	if err := validate.Required("uid", "body", m.UID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1ShootStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1ShootStatus) UnmarshalBinary(b []byte) error {
	var res V1beta1ShootStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
