// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1beta1LastError v1beta1 last error
// swagger:model v1beta1.LastError
type V1beta1LastError struct {

	// codes
	Codes []V1beta1ErrorCode `json:"codes"`

	// description
	// Required: true
	Description *string `json:"description"`

	// last update time
	LastUpdateTime string `json:"lastUpdateTime,omitempty"`

	// task ID
	TaskID string `json:"taskID,omitempty"`
}

// Validate validates this v1beta1 last error
func (m *V1beta1LastError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1LastError) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1LastError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1LastError) UnmarshalBinary(b []byte) error {
	var res V1beta1LastError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
