// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1beta1ObservabilityRotation v1beta1 observability rotation
//
// swagger:model v1beta1.ObservabilityRotation
type V1beta1ObservabilityRotation struct {

	// last completion time
	LastCompletionTime string `json:"lastCompletionTime,omitempty"`

	// last initiation time
	LastInitiationTime string `json:"lastInitiationTime,omitempty"`
}

// Validate validates this v1beta1 observability rotation
func (m *V1beta1ObservabilityRotation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1beta1 observability rotation based on context it is used
func (m *V1beta1ObservabilityRotation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1ObservabilityRotation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1ObservabilityRotation) UnmarshalBinary(b []byte) error {
	var res V1beta1ObservabilityRotation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
