// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V1beta1KubeProxyConfig v1beta1 kube proxy config
// swagger:model v1beta1.KubeProxyConfig
type V1beta1KubeProxyConfig struct {

	// feature gates
	FeatureGates map[string]bool `json:"featureGates,omitempty"`

	// mode
	Mode V1beta1ProxyMode `json:"mode,omitempty"`
}

// Validate validates this v1beta1 kube proxy config
func (m *V1beta1KubeProxyConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1KubeProxyConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1KubeProxyConfig) UnmarshalBinary(b []byte) error {
	var res V1beta1KubeProxyConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
