// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V1beta1OpenIDConnectClientAuthentication v1beta1 open ID connect client authentication
// swagger:model v1beta1.OpenIDConnectClientAuthentication
type V1beta1OpenIDConnectClientAuthentication struct {

	// extra config
	ExtraConfig map[string]string `json:"extraConfig,omitempty"`

	// secret
	Secret string `json:"secret,omitempty"`
}

// Validate validates this v1beta1 open ID connect client authentication
func (m *V1beta1OpenIDConnectClientAuthentication) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1OpenIDConnectClientAuthentication) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1OpenIDConnectClientAuthentication) UnmarshalBinary(b []byte) error {
	var res V1beta1OpenIDConnectClientAuthentication
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
