// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1beta1ManualWorkerPoolRollout v1beta1 manual worker pool rollout
//
// swagger:model v1beta1.ManualWorkerPoolRollout
type V1beta1ManualWorkerPoolRollout struct {

	// pending workers rollouts
	PendingWorkersRollouts []*V1beta1PendingWorkersRollout `json:"pendingWorkersRollouts"`
}

// Validate validates this v1beta1 manual worker pool rollout
func (m *V1beta1ManualWorkerPoolRollout) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePendingWorkersRollouts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1ManualWorkerPoolRollout) validatePendingWorkersRollouts(formats strfmt.Registry) error {
	if swag.IsZero(m.PendingWorkersRollouts) { // not required
		return nil
	}

	for i := 0; i < len(m.PendingWorkersRollouts); i++ {
		if swag.IsZero(m.PendingWorkersRollouts[i]) { // not required
			continue
		}

		if m.PendingWorkersRollouts[i] != nil {
			if err := m.PendingWorkersRollouts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pendingWorkersRollouts" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("pendingWorkersRollouts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1beta1 manual worker pool rollout based on the context it is used
func (m *V1beta1ManualWorkerPoolRollout) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePendingWorkersRollouts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1ManualWorkerPoolRollout) contextValidatePendingWorkersRollouts(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PendingWorkersRollouts); i++ {

		if m.PendingWorkersRollouts[i] != nil {

			if swag.IsZero(m.PendingWorkersRollouts[i]) { // not required
				return nil
			}

			if err := m.PendingWorkersRollouts[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pendingWorkersRollouts" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("pendingWorkersRollouts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1ManualWorkerPoolRollout) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1ManualWorkerPoolRollout) UnmarshalBinary(b []byte) error {
	var res V1beta1ManualWorkerPoolRollout
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
