name: Auto Generate

on:
  push:
    branches:
      - auto-generate/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Generate
      run: |
        make generate-client

    - name: Push
      run: |
        git config --global user.name "auto-build"
        git config --global user.email "info@metal-stack.io"
        git add .
        git commit -m "Bump to next version"
        git push
