name: Auto Generate

on:
  push:
    branches:
      - auto-generate/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Generate
      run: |
        go install github.com/mikefarah/yq/v4@latest
        make
      env:
        GENERATE_TOKEN: ${{ secrets.GENERATE_TOKEN }}

    - name: Push
      run: |
        if ! git diff --exit-code; then
          git config --global user.name "auto-build"
          git config --global user.email "info@metal-stack.io"
          git add .
          git commit -m "Bump to version $(cat VERSION)"
          git push
        fi
