name: build

on:
  push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v8

    - name: Build
      run: make test
